### ISSUE TITLE
Function Prototypes

### ISSUE THREAD

**Issue by nathasm** [BrianArne/C-Bootcamp#2]
Take in 3 values from the user and perform basic operations on them. Define function prototypes for input, sum, average, largest, smallest. Input should take 3 values, passed by reference. The sum, average, largest, smallest should take 4 values, with the input values passed by value, and the result passed by reference. Manipulate the output stream so that it always shows the decimal place using fixed floating-point notation with at most 3 significant digits

**Comment by BrianArne** [comment]
Solution Committed.

**Comment by nathasm** [comment]
1) If you're going to use templates, it's good practice to define the passed in types regardless of what the compiler coerces your values to.
2) You should be passing by reference instead of pointers. [This](https://www.geeksforgeeks.org/passing-by-pointer-vs-passing-by-reference-in-c/) does a pretty good job explaining the differences. For your case, you aren't changing the pointer to be NULL ever and you're not iterating over a memory location.

**Comment by BrianArne** [comment]
Fixed and Closed
