### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by nathasm** [BrianArne/C-Bootcamp#4]
This will be your first 'big' project:

Implement a dice game with two players. The goal is to get the highest score out of 6 dice in 3 rolls. You present the user an ASCII drawing of the 6 dice and let them re-roll as many of the 6 dice as they want. They can do this 3 times in an attempt to get the highest score.

- Create a Dice class that stores a value and how to print ASCII for each value
- Create a DieValue enum that allows you to convert a number to an enum value and use it to figure out which die you should change
- Create a Player class which should handle all aspects for a player (dice, asking for input, displaying output, input on which dice to change, accessing sum for the player)
- You will need to create ASCII art representing each value of a dice (1-6)
- The main should handle getting all input from player 1, then all input from player 2. Then displaying the results.

**Comment by BrianArne** [comment]
Closed
